from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(920, 821)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 920, 800))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 30, 901, 51))
        self.label.setStyleSheet("background-color : blue")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(90, 160, 741, 71))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.comComboBox = QtWidgets.QComboBox(self.tab)
        self.comComboBox.setGeometry(QtCore.QRect(390, 310, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.comComboBox.setFont(font)
        self.comComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comComboBox.setIconSize(QtCore.QSize(14, 14))
        self.comComboBox.setObjectName("comComboBox")
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(0, 80, 911, 20))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.line_3.setFont(font)
        self.line_3.setLineWidth(3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(0, 30, 920, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(self.tab_2)
        self.line.setGeometry(QtCore.QRect(0, 80, 911, 20))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(0, 110, 920, 41))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLineWidth(1)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_4.setStyleSheet("background-color : YELLOW")
        self.dispTemp = QtWidgets.QLabel(self.tab_2)
        self.dispTemp.setGeometry(QtCore.QRect(429, 170, 281, 38))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(17)
        self.dispTemp.setFont(font)
        self.dispTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.dispTemp.setObjectName("dispTemp")
        self.getTemperature1 = QtWidgets.QPushButton(self.tab_2)
        self.getTemperature1.setGeometry(QtCore.QRect(390, 300, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.getTemperature1.setFont(font)
        self.getTemperature1.setObjectName("getTemperature1")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(180, 170, 260, 38))
        self.getTemperature1.setStyleSheet("background-color : blue")
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(17)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.startAir = QtWidgets.QPushButton(self.tab_2)
        self.startAir.setGeometry(QtCore.QRect(140, 570, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.startAir.setFont(font)
        self.startAir.setStyleSheet("background-color : yellow")
        self.startAir.setObjectName("startAir")
        self.StopAir = QtWidgets.QPushButton(self.tab_2)
        self.StopAir.setGeometry(QtCore.QRect(620, 570, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.StopAir.setStyleSheet("background-color : yellow")
        self.StopAir.setFont(font)
        self.StopAir.setObjectName("StopAir")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(180, 230, 260, 38))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(17)

        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.dispHum = QtWidgets.QLabel(self.tab_2)
        self.dispHum.setGeometry(QtCore.QRect(429, 230, 281, 31))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(18)
        self.dispHum.setFont(font)
        self.dispHum.setAlignment(QtCore.Qt.AlignCenter)
        self.dispHum.setObjectName("dispHum")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 920, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Your COM-port"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Ports"))
        self.label_3.setText(_translate("MainWindow", "Climate control"))
        self.label_4.setText(_translate("MainWindow", " Your ROOM "))
        self.dispTemp.setText(_translate("MainWindow", "No data"))
        self.getTemperature1.setText(_translate("MainWindow", "Get Data"))
        self.label_5.setText(_translate("MainWindow", "Temperature is"))
        self.startAir.setText(_translate("MainWindow", "Start"))
        self.StopAir.setText(_translate("MainWindow", "Stop"))
        self.label_8.setText(_translate("MainWindow", "Humidity is"))
        self.dispHum.setText(_translate("MainWindow", "No data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Room 1"))
